/**
 * Mock fixture data for RayCash dashboard (Track C)
 * Satisfies type contracts from lib/types.ts
 * Used until Track B wires the real API.
 */

import type {
  BudgetStatus,
  GoalStatus,
  MonthlyReport,
  Transaction,
  RecurringCandidate,
} from "./types";

// ---------------------------------------------------------------------------
// mockBudgetStatuses
// ---------------------------------------------------------------------------

export const mockBudgetStatuses: BudgetStatus[] = [
  {
    budget_id: "bud_001",
    category: "FOOD_AND_DRINK",
    limit: 400,
    spent: 312.5,
    remaining: 87.5,
    pct_used: 78.1,
    projected_end_of_period: 385.0,
    status: "warning",
  },
  {
    budget_id: "bud_002",
    category: "TRANSPORTATION",
    limit: 150,
    spent: 61.0,
    remaining: 89.0,
    pct_used: 40.7,
    projected_end_of_period: 75.0,
    status: "under",
  },
  {
    budget_id: "bud_003",
    category: "ENTERTAINMENT",
    limit: 100,
    spent: 134.99,
    remaining: -34.99,
    pct_used: 135.0,
    projected_end_of_period: 165.0,
    status: "over",
  },
  {
    budget_id: "bud_004",
    category: "GENERAL_MERCHANDISE",
    limit: 200,
    spent: 88.45,
    remaining: 111.55,
    pct_used: 44.2,
    projected_end_of_period: 108.0,
    status: "under",
  },
  {
    budget_id: "bud_005",
    category: "PERSONAL_CARE",
    limit: 60,
    spent: 52.0,
    remaining: 8.0,
    pct_used: 86.7,
    projected_end_of_period: 63.5,
    status: "warning",
  },
];

// ---------------------------------------------------------------------------
// mockGoalStatuses
// ---------------------------------------------------------------------------

export const mockGoalStatuses: GoalStatus[] = [
  {
    goal_id: "goal_001",
    name: "Emergency Fund",
    target: 3000,
    saved: 1250,
    remaining: 1750,
    pct: 41.7,
    deadline: "2026-12-31",
    weeks_left: 30,
    required_weekly: 58.33,
    on_track: true,
  },
  {
    goal_id: "goal_002",
    name: "New Laptop",
    target: 1200,
    saved: 320,
    remaining: 880,
    pct: 26.7,
    deadline: "2026-09-01",
    weeks_left: 13,
    required_weekly: 67.69,
    on_track: false,
  },
  {
    goal_id: "goal_003",
    name: "Spring Break Trip",
    target: 800,
    saved: 680,
    remaining: 120,
    pct: 85.0,
    deadline: "2026-03-15",
    weeks_left: null,
    required_weekly: null,
    on_track: true,
  },
];

// ---------------------------------------------------------------------------
// mockMonthlyReport
// ---------------------------------------------------------------------------

export const mockMonthlyReport: MonthlyReport = {
  period: "2026-05",
  totals_by_category: {
    FOOD_AND_DRINK: 312.5,
    TRANSPORTATION: 61.0,
    ENTERTAINMENT: 134.99,
    GENERAL_MERCHANDISE: 88.45,
    PERSONAL_CARE: 52.0,
    UTILITIES: 95.0,
    EDUCATION: 45.0,
    TRAVEL: 0,
  },
  total_spent: 788.94,
  vs_prior_month: {
    delta: 63.21,
    pct: 8.7,
  },
  budgets: mockBudgetStatuses,
  top_movers: [
    {
      category: "ENTERTAINMENT",
      current: 134.99,
      prior: 40.0,
      delta: 94.99,
      pct: 237.5,
    },
    {
      category: "FOOD_AND_DRINK",
      current: 312.5,
      prior: 290.0,
      delta: 22.5,
      pct: 7.8,
    },
    {
      category: "PERSONAL_CARE",
      current: 52.0,
      prior: 72.0,
      delta: -20.0,
      pct: -27.8,
    },
  ],
};

// ---------------------------------------------------------------------------
// mockTransactions — 20+ transactions across 3 months and 5 categories
// ---------------------------------------------------------------------------

export const mockTransactions: Transaction[] = [
  // March 2026
  {
    id: "tx_001",
    user_id: "user_demo",
    item_id: "item_001",
    plaid_transaction_id: "plaid_001",
    amount: -12.5,
    merchant_name: "Chick-fil-A",
    category: "FOOD_AND_DRINK",
    date: "2026-03-03",
    posted: true,
  },
  {
    id: "tx_002",
    user_id: "user_demo",
    item_id: "item_001",
    plaid_transaction_id: "plaid_002",
    amount: -2.75,
    merchant_name: "CapMetro",
    category: "TRANSPORTATION",
    date: "2026-03-05",
    posted: true,
  },
  {
    id: "tx_003",
    user_id: "user_demo",
    item_id: "item_001",
    plaid_transaction_id: "plaid_003",
    amount: -14.99,
    merchant_name: "Netflix",
    category: "ENTERTAINMENT",
    date: "2026-03-07",
    posted: true,
  },
  {
    id: "tx_004",
    user_id: "user_demo",
    item_id: "item_001",
    plaid_transaction_id: "plaid_004",
    amount: -38.0,
    merchant_name: "H-E-B",
    category: "GENERAL_MERCHANDISE",
    date: "2026-03-10",
    posted: true,
  },
  {
    id: "tx_005",
    user_id: "user_demo",
    item_id: "item_001",
    plaid_transaction_id: "plaid_005",
    amount: -24.5,
    merchant_name: "Torchy's Tacos",
    category: "FOOD_AND_DRINK",
    date: "2026-03-14",
    posted: true,
  },
  {
    id: "tx_006",
    user_id: "user_demo",
    item_id: "item_001",
    plaid_transaction_id: "plaid_006",
    amount: -15.0,
    merchant_name: "Uber",
    category: "TRANSPORTATION",
    date: "2026-03-18",
    posted: true,
  },
  {
    id: "tx_007",
    user_id: "user_demo",
    item_id: "item_001",
    plaid_transaction_id: "plaid_007",
    amount: -9.99,
    merchant_name: "Spotify",
    category: "ENTERTAINMENT",
    date: "2026-03-22",
    posted: true,
  },
  {
    id: "tx_008",
    user_id: "user_demo",
    item_id: "item_001",
    plaid_transaction_id: "plaid_008",
    amount: -42.0,
    merchant_name: "Target",
    category: "GENERAL_MERCHANDISE",
    date: "2026-03-27",
    posted: true,
  },
  // April 2026
  {
    id: "tx_009",
    user_id: "user_demo",
    item_id: "item_001",
    plaid_transaction_id: "plaid_009",
    amount: -18.75,
    merchant_name: "McDonald's",
    category: "FOOD_AND_DRINK",
    date: "2026-04-02",
    posted: true,
  },
  {
    id: "tx_010",
    user_id: "user_demo",
    item_id: "item_001",
    plaid_transaction_id: "plaid_010",
    amount: -22.0,
    merchant_name: "Lyft",
    category: "TRANSPORTATION",
    date: "2026-04-06",
    posted: true,
  },
  {
    id: "tx_011",
    user_id: "user_demo",
    item_id: "item_001",
    plaid_transaction_id: "plaid_011",
    amount: -110.0,
    merchant_name: "Alamo Drafthouse",
    category: "ENTERTAINMENT",
    date: "2026-04-11",
    posted: true,
  },
  {
    id: "tx_012",
    user_id: "user_demo",
    item_id: "item_001",
    plaid_transaction_id: "plaid_012",
    amount: -55.0,
    merchant_name: "Whole Foods",
    category: "FOOD_AND_DRINK",
    date: "2026-04-15",
    posted: true,
  },
  {
    id: "tx_013",
    user_id: "user_demo",
    item_id: "item_001",
    plaid_transaction_id: "plaid_013",
    amount: -30.0,
    merchant_name: "Amazon",
    category: "GENERAL_MERCHANDISE",
    date: "2026-04-19",
    posted: true,
  },
  {
    id: "tx_014",
    user_id: "user_demo",
    item_id: "item_001",
    plaid_transaction_id: "plaid_014",
    amount: -27.5,
    merchant_name: "Panda Express",
    category: "FOOD_AND_DRINK",
    date: "2026-04-23",
    posted: true,
  },
  {
    id: "tx_015",
    user_id: "user_demo",
    item_id: "item_001",
    plaid_transaction_id: "plaid_015",
    amount: -8.5,
    merchant_name: "CapMetro",
    category: "TRANSPORTATION",
    date: "2026-04-27",
    posted: true,
  },
  // May 2026
  {
    id: "tx_016",
    user_id: "user_demo",
    item_id: "item_001",
    plaid_transaction_id: "plaid_016",
    amount: -62.0,
    merchant_name: "H-E-B",
    category: "FOOD_AND_DRINK",
    date: "2026-05-03",
    posted: true,
  },
  {
    id: "tx_017",
    user_id: "user_demo",
    item_id: "item_001",
    plaid_transaction_id: "plaid_017",
    amount: -14.99,
    merchant_name: "Netflix",
    category: "ENTERTAINMENT",
    date: "2026-05-07",
    posted: true,
  },
  {
    id: "tx_018",
    user_id: "user_demo",
    item_id: "item_001",
    plaid_transaction_id: "plaid_018",
    amount: -120.0,
    merchant_name: "Spotify + Concert Tickets",
    category: "ENTERTAINMENT",
    date: "2026-05-12",
    posted: true,
  },
  {
    id: "tx_019",
    user_id: "user_demo",
    item_id: "item_001",
    plaid_transaction_id: "plaid_019",
    amount: -48.5,
    merchant_name: "Torchy's Tacos",
    category: "FOOD_AND_DRINK",
    date: "2026-05-17",
    posted: true,
  },
  {
    id: "tx_020",
    user_id: "user_demo",
    item_id: "item_001",
    plaid_transaction_id: "plaid_020",
    amount: -35.0,
    merchant_name: "CVS Pharmacy",
    category: "PERSONAL_CARE",
    date: "2026-05-21",
    posted: true,
  },
  {
    id: "tx_021",
    user_id: "user_demo",
    item_id: "item_001",
    plaid_transaction_id: "plaid_021",
    amount: -18.0,
    merchant_name: "Lyft",
    category: "TRANSPORTATION",
    date: "2026-05-25",
    posted: true,
  },
  {
    id: "tx_022",
    user_id: "user_demo",
    item_id: "item_001",
    plaid_transaction_id: "plaid_022",
    amount: -22.0,
    merchant_name: "Campus Bookstore",
    category: "EDUCATION",
    date: "2026-05-28",
    posted: true,
  },
];

// ---------------------------------------------------------------------------
// mockRecurring
// ---------------------------------------------------------------------------

export const mockRecurring: RecurringCandidate[] = [
  {
    merchant: "Netflix",
    typical_amount: 14.99,
    cadence_days: 30,
    confidence: 0.98,
    sample_count: 5,
  },
  {
    merchant: "Spotify",
    typical_amount: 9.99,
    cadence_days: 30,
    confidence: 0.95,
    sample_count: 4,
  },
  {
    merchant: "CapMetro",
    typical_amount: 2.75,
    cadence_days: 3,
    confidence: 0.82,
    sample_count: 12,
  },
];
